### ISSUE TITLE
Thank you for this tool !

### ISSUE THREAD

**Issue by 12343954** [xattacker/AppPushTestForm#1]
i tested , and found that my .p12 file was wrong export place !

the .p12 file only export from private key in key chain !

**Comment by xattacker** [comment]
Yes
In my case, I only select private key to export a .p12 file, not whole certificate.
And I use the .p12 file to push

**Comment by xattacker** [comment]
Hello,
p8 Auth Key mode is supported now.

**Comment by 12343954** [comment]
good job, bro!
